#!/bin/bash
set -e

# === WoW Backup ===
# Databases backed up:
#   acore_auth        - CRITICAL: accounts
#   acore_characters  - CRITICAL: character progress
#
# Intentionally excluded:
#   acore_world       - auto-regenerated by worldserver on first start
#   acore_playerbots  - bot state only, acceptable to lose
#
# Retention (count-based, safe for irregular backup schedules):
#   Local backups:  keep last KEEP_LOCAL_COUNT
#   Drive backups:  keep last KEEP_DRIVE_COUNT

# === PATHS ===
FULL_BASE="/home/deck/azerothcore/backups"
SCREENSHOT_SRC="/home/deck/.steam/steam/userdata/1631191323/760/remote/15764481545068347392/screenshots"
GDRIVE_REMOTE="wow-backup:wow-backup"

# === SETTINGS ===
KEEP_LOCAL_COUNT=10   # Keep this many most-recent local backups
KEEP_DRIVE_COUNT=20   # Keep this many most-recent Drive backups

TIMESTAMP=$(date +%F_%H-%M)
BACKUP_DIR="$FULL_BASE/$TIMESTAMP"

# ── STEP 0: Stop servers ──────────────────────────────────────────────────────
echo
echo "[0/4] Stopping servers..."

if pgrep -x worldserver > /dev/null; then
  echo "  Stopping worldserver..."
  pkill -SIGINT -f "worldserver"
  echo "  Waiting for worldserver to shut down..."
  while pgrep -x worldserver > /dev/null; do
    sleep 1
  done
  echo "  ✅ worldserver stopped."
else
  echo "  worldserver not running — skipping."
fi

if pgrep -x authserver > /dev/null; then
  echo "  Stopping authserver..."
  pkill -SIGINT -f "authserver"
  echo "  Waiting for authserver to shut down..."
  while pgrep -x authserver > /dev/null; do
    sleep 1
  done
  echo "  ✅ authserver stopped."
else
  echo "  authserver not running — skipping."
fi

mkdir -p "$BACKUP_DIR" || { echo "Failed to create backup dir"; exit 1; }

echo "======================================="
echo "WoW Backup Started"
echo "Timestamp: $TIMESTAMP"
echo "Backup dir: $BACKUP_DIR"
echo "======================================="

# ── STEP 1: Dump databases ───────────────────────────────────────────────────
echo
echo "[1/4] Dumping databases..."

echo "  Dumping acore_auth..."
mysqldump --no-tablespaces -h 127.0.0.1 -u acore -pacore acore_auth \
  > "$BACKUP_DIR/acore_auth.sql" || { echo "Failed: acore_auth dump"; exit 1; }

echo "  Dumping acore_characters..."
mysqldump --no-tablespaces -h 127.0.0.1 -u acore -pacore acore_characters \
  > "$BACKUP_DIR/acore_characters.sql" || { echo "Failed: acore_characters dump"; exit 1; }

echo "  Saving progress report..."

{
  echo "=== Server Version ==="
  echo "AzerothCore last update: $(cd /home/deck/azerothcore && git log -1 --format='%ci')"
  echo "Playerbots last update: $(cd /home/deck/azerothcore/modules/mod-playerbots && git log -1 --format='%ci')"
  echo

  echo "=== Alliance ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT
      CONCAT(
        c.name, ': ',
        CASE c.race
          WHEN 1 THEN 'Human' WHEN 3 THEN 'Dwarf' WHEN 4 THEN 'Night Elf'
          WHEN 7 THEN 'Gnome' WHEN 11 THEN 'Draenei' ELSE 'Unknown'
        END, ', ',
        CASE c.class
          WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter'
          WHEN 4 THEN 'Rogue' WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight'
          WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage' WHEN 9 THEN 'Warlock'
          WHEN 11 THEN 'Druid' ELSE 'Unknown'
        END,
        ' | Level: ', c.level,
        ' | Money: ', FLOOR(c.money / 10000), 'g',
        ' | Achievements: ', COALESCE(cap.total_points, 0), 'pts (', COALESCE(cap.total_achievements, 0), ')',
        ' | Played: ', FLOOR(c.totaltime / 3600), 'hrs'
      )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (1,3,4,7,11)
    ORDER BY c.totaltime DESC;
  "

  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Total: Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (1,3,4,7,11);
  "

  echo
  echo "=== Horde ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT
      CONCAT(
        c.name, ': ',
        CASE c.race
          WHEN 2 THEN 'Orc' WHEN 5 THEN 'Undead' WHEN 6 THEN 'Tauren'
          WHEN 8 THEN 'Troll' WHEN 9 THEN 'Goblin' WHEN 10 THEN 'Blood Elf' ELSE 'Unknown'
        END, ', ',
        CASE c.class
          WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter'
          WHEN 4 THEN 'Rogue' WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight'
          WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage' WHEN 9 THEN 'Warlock'
          WHEN 11 THEN 'Druid' ELSE 'Unknown'
        END,
        ' | Level: ', c.level,
        ' | Money: ', FLOOR(c.money / 10000), 'g',
        ' | Achievements: ', COALESCE(cap.total_points, 0), 'pts (', COALESCE(cap.total_achievements, 0), ')',
        ' | Played: ', FLOOR(c.totaltime / 3600), 'hrs'
      )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (2,5,6,8,9,10)
    ORDER BY c.totaltime DESC;
  "

  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Total: Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (2,5,6,8,9,10);
  "

  echo
  echo "=== Grand Total ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%';
  "
} > "$BACKUP_DIR/playtime_by_character.txt" || { echo "Failed: progress report export"; exit 1; }

echo "  Saving characters.json..."
REPO_DATA_DIR="/home/deck/wow-companion-data"
ACHIEVEMENTS_TMP="$(mktemp)"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ca.guid, ca.achievement
  FROM acore_characters.character_achievement ca
  JOIN acore_characters.characters c ON c.guid = ca.guid
  JOIN acore_auth.account a ON a.id = c.account
  WHERE a.username NOT LIKE 'RNDBOT%';
" > "$ACHIEVEMENTS_TMP"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT
    c.guid,
    c.name,
    a.username,
    c.race,
    CASE c.race
      WHEN 1 THEN 'Human' WHEN 2 THEN 'Orc' WHEN 3 THEN 'Dwarf' WHEN 4 THEN 'Night Elf'
      WHEN 5 THEN 'Undead' WHEN 6 THEN 'Tauren' WHEN 7 THEN 'Gnome' WHEN 8 THEN 'Troll'
      WHEN 9 THEN 'Goblin' WHEN 10 THEN 'Blood Elf' WHEN 11 THEN 'Draenei'
      ELSE 'Unknown'
    END,
    c.class,
    CASE c.class
      WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter' WHEN 4 THEN 'Rogue'
      WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight' WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage'
      WHEN 9 THEN 'Warlock' WHEN 11 THEN 'Druid'
      ELSE 'Unknown'
    END,
    CASE
      WHEN c.race IN (1,3,4,7,11) THEN 'Alliance'
      WHEN c.race IN (2,5,6,8,9,10) THEN 'Horde'
      ELSE 'Unknown'
    END,
    c.level,
    c.money,
    COALESCE(cap.total_points, 0),
    COALESCE(cap.total_achievements, 0),
    c.totaltime
  FROM acore_characters.characters c
  JOIN acore_auth.account a ON a.id = c.account
  LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
  WHERE a.username NOT LIKE 'RNDBOT%'
  ORDER BY c.totaltime DESC;
" | python3 -c "
import sys, json, datetime
from collections import defaultdict

achievements_by_guid = defaultdict(list)
with open('$ACHIEVEMENTS_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, achievement_id = line.split('\t')
        achievements_by_guid[int(guid)].append(int(achievement_id))

characters = []
for line in sys.stdin:
    line = line.rstrip('\n')
    if not line:
        continue
    (guid, name, account, race, race_name, cls, class_name,
     faction, level, money, ap, ac, played) = line.split('\t')
    guid = int(guid)
    characters.append({
        'guid': guid,
        'name': name,
        'account': account,
        'race_id': int(race),
        'race_name': race_name,
        'class_id': int(cls),
        'class_name': class_name,
        'faction': faction,
        'level': int(level),
        'money_copper': int(money),
        'achievement_points': int(ap),
        'achievement_count': int(ac),
        'played_time_seconds': int(played),
        'achievements': sorted(achievements_by_guid.get(guid, [])),
    })

generated_at = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

with open('$BACKUP_DIR/characters.json', 'w') as f:
    json.dump({'generated_at': generated_at, 'characters': characters}, f, indent=2)

public_characters = [{k: v for k, v in c.items() if k != 'account'} for c in characters]
with open('$REPO_DATA_DIR/characters.json', 'w') as f:
    json.dump({'generated_at': generated_at, 'characters': public_characters}, f, indent=2)

print(f'  characters.json: wrote {len(characters)} characters')
" || { echo "Failed: characters.json export"; exit 1; }
rm -f "$ACHIEVEMENTS_TMP"

echo "  Publishing characters.json to GitHub..."
(
  cd "$REPO_DATA_DIR" \
    && git add characters.json \
    && if ! git diff --cached --quiet; then
         git commit -m "Update character data $TIMESTAMP" \
           && git push origin main
       else
         echo "  No character data changes to publish."
       fi
) || echo "  Warning: failed to publish characters.json to GitHub (non-fatal)"

echo "  Compressing..."
gzip "$BACKUP_DIR"/*.sql || { echo "Failed to compress"; exit 1; }

echo "  Local backup complete: $BACKUP_DIR"

# ── STEP 2: Upload to Google Drive ───────────────────────────────────────────
echo
echo "[2/4] Uploading to Google Drive..."
rclone copy "$BACKUP_DIR" "$GDRIVE_REMOTE/backups/$TIMESTAMP" --progress \
  || { echo "Google Drive upload failed"; exit 1; }

# ── STEP 3: Screenshots ───────────────────────────────────────────────────────
echo
echo "[3/4] Syncing screenshots to Google Drive..."
rclone copy "$SCREENSHOT_SRC" "$GDRIVE_REMOTE/screenshots" --progress \
  || { echo "Google Drive screenshot sync failed"; exit 1; }

# ── STEP 4: Rotate old backups (count-based) ──────────────────────────────────
echo
echo "[4/4] Rotating old backups..."

echo "  Keeping latest $KEEP_LOCAL_COUNT local backups..."
ls -1dt "$FULL_BASE"/*/ | tail -n +$((KEEP_LOCAL_COUNT + 1)) | xargs -r rm -rf \
  && echo "  Local rotation done." \
  || echo "  Warning: local rotation had issues (non-fatal)"

echo "  Keeping latest $KEEP_DRIVE_COUNT Drive backups..."
DRIVE_DIRS=$(rclone lsf "$GDRIVE_REMOTE/backups/" --dirs-only | sort | head -n -$KEEP_DRIVE_COUNT)
if [ -n "$DRIVE_DIRS" ]; then
  echo "$DRIVE_DIRS" | while read -r dir; do
    rclone purge "$GDRIVE_REMOTE/backups/$dir" \
      && echo "  Deleted Drive backup: $dir" \
      || echo "  Warning: failed to delete $dir (non-fatal)"
  done
else
  echo "  No Drive backups to prune."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "======================================="
echo "Backup Complete!"
echo "  Local: $BACKUP_DIR"
echo "  Drive: $GDRIVE_REMOTE/backups/$TIMESTAMP"
echo "  Drive screenshots: $GDRIVE_REMOTE/screenshots"
echo "======================================="
echo
echo "Progress:"
cat "$BACKUP_DIR/playtime_by_character.txt"
echo
echo "Backup contents:"
ls -lh "$BACKUP_DIR"
