#!/bin/bash
set -e

# === WoW Backup ===
# Databases backed up:
#   acore_auth        - CRITICAL: accounts
#   acore_characters  - CRITICAL: character progress
#
# Intentionally excluded:
#   acore_world       - auto-regenerated by worldserver on first start
#   acore_playerbots  - bot state only, acceptable to lose
#
# Retention (count-based, safe for irregular backup schedules):
#   Local backups:  keep last KEEP_LOCAL_COUNT
#   Drive backups:  keep last KEEP_DRIVE_COUNT

# === PATHS ===
FULL_BASE="/home/deck/azerothcore/backups"
SCREENSHOT_SRC="/home/deck/.steam/steam/userdata/1631191323/760/remote/15764481545068347392/screenshots"
GDRIVE_REMOTE="wow-backup:wow-backup"

# === SETTINGS ===
KEEP_LOCAL_COUNT=10   # Keep this many most-recent local backups
KEEP_DRIVE_COUNT=20   # Keep this many most-recent Drive backups

TIMESTAMP=$(date +%F_%H-%M)
BACKUP_DIR="$FULL_BASE/$TIMESTAMP"

# ── STEP 0: Stop servers ──────────────────────────────────────────────────────
echo
echo "[0/4] Stopping servers..."

if pgrep -x worldserver > /dev/null; then
  echo "  Stopping worldserver..."
  pkill -SIGINT -f "worldserver"
  echo "  Waiting for worldserver to shut down..."
  while pgrep -x worldserver > /dev/null; do
    sleep 1
  done
  echo "  ✅ worldserver stopped."
else
  echo "  worldserver not running — skipping."
fi

if pgrep -x authserver > /dev/null; then
  echo "  Stopping authserver..."
  pkill -SIGINT -f "authserver"
  echo "  Waiting for authserver to shut down..."
  while pgrep -x authserver > /dev/null; do
    sleep 1
  done
  echo "  ✅ authserver stopped."
else
  echo "  authserver not running — skipping."
fi

mkdir -p "$BACKUP_DIR" || { echo "Failed to create backup dir"; exit 1; }

echo "======================================="
echo "WoW Backup Started"
echo "Timestamp: $TIMESTAMP"
echo "Backup dir: $BACKUP_DIR"
echo "======================================="

# ── STEP 1: Dump databases ───────────────────────────────────────────────────
echo
echo "[1/4] Dumping databases..."

echo "  Dumping acore_auth..."
mysqldump --no-tablespaces -h 127.0.0.1 -u acore -pacore acore_auth \
  > "$BACKUP_DIR/acore_auth.sql" || { echo "Failed: acore_auth dump"; exit 1; }

echo "  Dumping acore_characters..."
mysqldump --no-tablespaces -h 127.0.0.1 -u acore -pacore acore_characters \
  > "$BACKUP_DIR/acore_characters.sql" || { echo "Failed: acore_characters dump"; exit 1; }

echo "  Saving progress report..."

{
  echo "=== Server Version ==="
  echo "AzerothCore last update: $(cd /home/deck/azerothcore && git log -1 --format='%ci')"
  echo "Playerbots last update: $(cd /home/deck/azerothcore/modules/mod-playerbots && git log -1 --format='%ci')"
  echo

  echo "=== Alliance ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT
      CONCAT(
        c.name, ': ',
        CASE c.race
          WHEN 1 THEN 'Human' WHEN 3 THEN 'Dwarf' WHEN 4 THEN 'Night Elf'
          WHEN 7 THEN 'Gnome' WHEN 11 THEN 'Draenei' ELSE 'Unknown'
        END, ', ',
        CASE c.class
          WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter'
          WHEN 4 THEN 'Rogue' WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight'
          WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage' WHEN 9 THEN 'Warlock'
          WHEN 11 THEN 'Druid' ELSE 'Unknown'
        END,
        ' | Level: ', c.level,
        ' | Money: ', FLOOR(c.money / 10000), 'g',
        ' | Achievements: ', COALESCE(cap.total_points, 0), 'pts (', COALESCE(cap.total_achievements, 0), ')',
        ' | Played: ', FLOOR(c.totaltime / 3600), 'hrs'
      )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (1,3,4,7,11)
    ORDER BY c.totaltime DESC;
  "

  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Total: Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (1,3,4,7,11);
  "

  echo
  echo "=== Horde ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT
      CONCAT(
        c.name, ': ',
        CASE c.race
          WHEN 2 THEN 'Orc' WHEN 5 THEN 'Undead' WHEN 6 THEN 'Tauren'
          WHEN 8 THEN 'Troll' WHEN 9 THEN 'Goblin' WHEN 10 THEN 'Blood Elf' ELSE 'Unknown'
        END, ', ',
        CASE c.class
          WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter'
          WHEN 4 THEN 'Rogue' WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight'
          WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage' WHEN 9 THEN 'Warlock'
          WHEN 11 THEN 'Druid' ELSE 'Unknown'
        END,
        ' | Level: ', c.level,
        ' | Money: ', FLOOR(c.money / 10000), 'g',
        ' | Achievements: ', COALESCE(cap.total_points, 0), 'pts (', COALESCE(cap.total_achievements, 0), ')',
        ' | Played: ', FLOOR(c.totaltime / 3600), 'hrs'
      )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (2,5,6,8,9,10)
    ORDER BY c.totaltime DESC;
  "

  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Total: Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (2,5,6,8,9,10);
  "

  echo
  echo "=== Grand Total ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%';
  "
} > "$BACKUP_DIR/playtime_by_character.txt" || { echo "Failed: progress report export"; exit 1; }

echo "  Saving characters.json..."
REPO_DATA_DIR="/home/deck/wow-armory-data"

# Sync the clone to the latest published state before touching anything in
# it — both so the sticky-collectable merge below reads the true latest
# characters.json (not a stale local copy), and so the commit+push at the
# end of this step is always a clean fast-forward instead of colliding with
# whatever else has been pushed to main since the last backup run (code
# changes, a rename, etc. — this directory is purely an auto-managed
# publish target, never hand-edited, so discarding any local state here is
# always safe).
(cd "$REPO_DATA_DIR" && git fetch origin main && git reset --hard origin/main) \
  || echo "  Warning: failed to sync $REPO_DATA_DIR with origin/main before publishing (non-fatal)"

COLLECTION_SETS_DEFS="$REPO_DATA_DIR/assets/data/collections/sets.json"
COLLECTION_MOUNTS_DEFS="$REPO_DATA_DIR/assets/data/collections/mounts.json"
COLLECTION_COMPANIONS_DEFS="$REPO_DATA_DIR/assets/data/collections/companions.json"
COLLECTION_LEGENDARIES_DEFS="$REPO_DATA_DIR/assets/data/collections/legendaries.json"
COLLECTION_TABARDS_DEFS="$REPO_DATA_DIR/assets/data/collections/tabards.json"
COLLECTION_HEIRLOOMS_DEFS="$REPO_DATA_DIR/assets/data/collections/heirlooms.json"
COLLECTION_TITLES_DEFS="$REPO_DATA_DIR/assets/data/collections/titles.json"
ACHIEVEMENTS_TMP="$(mktemp)"
EQUIPPED_TMP="$(mktemp)"
KNOWN_SPELLS_TMP="$(mktemp)"
ACHIEVEMENT_TITLES_TMP="$(mktemp)"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ca.guid, ca.achievement, ca.date
  FROM acore_characters.character_achievement ca
  JOIN acore_characters.characters c ON c.guid = ca.guid
  JOIN acore_auth.account a ON a.id = c.account
  WHERE a.username NOT LIKE 'RNDBOT%';
" > "$ACHIEVEMENTS_TMP"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ci.guid, ci.slot, ii.itemEntry, it.name
  FROM acore_characters.character_inventory ci
  JOIN acore_characters.item_instance ii ON ii.guid = ci.item
  JOIN acore_characters.characters c ON c.guid = ci.guid
  JOIN acore_auth.account a ON a.id = c.account
  JOIN acore_world.item_template it ON it.entry = ii.itemEntry
  WHERE ci.bag = 0 AND ci.slot BETWEEN 0 AND 18
    AND a.username NOT LIKE 'RNDBOT%';
" > "$EQUIPPED_TMP"
# Only the spell ids that actually matter for Mounts/Companions detection —
# a max-level character can know thousands of spells, so filtering
# server-side keeps this cheap. Both categories share this one query.
SPELL_COLLECTION_IDS="$(python3 -c "
import json
ids = set()
for path in ('$COLLECTION_MOUNTS_DEFS', '$COLLECTION_COMPANIONS_DEFS'):
    with open(path) as f:
        defs = json.load(f)
    ids.update(str(s) for d in defs for s in d['spell_ids'])
print(','.join(sorted(ids)) if ids else '0')
")"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT cs.guid, cs.spell
  FROM acore_characters.character_spell cs
  JOIN acore_characters.characters c ON c.guid = cs.guid
  JOIN acore_auth.account a ON a.id = c.account
  WHERE cs.spell IN ($SPELL_COLLECTION_IDS)
    AND a.username NOT LIKE 'RNDBOT%';
" > "$KNOWN_SPELLS_TMP"
# Which achievement grants which title, by faction — a small (~100 row)
# world-DB table, cheap to pull in full every run. Only rows that actually
# grant a title matter; TitleA/TitleH are real CharTitles ids (the same id
# space assets/data/collections/titles.json's own id uses), 0 = none.
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ID, TitleA, TitleH
  FROM acore_world.achievement_reward
  WHERE TitleA != 0 OR TitleH != 0;
" > "$ACHIEVEMENT_TITLES_TMP"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT
    c.guid,
    c.name,
    a.username,
    c.race,
    CASE c.race
      WHEN 1 THEN 'Human' WHEN 2 THEN 'Orc' WHEN 3 THEN 'Dwarf' WHEN 4 THEN 'Night Elf'
      WHEN 5 THEN 'Undead' WHEN 6 THEN 'Tauren' WHEN 7 THEN 'Gnome' WHEN 8 THEN 'Troll'
      WHEN 9 THEN 'Goblin' WHEN 10 THEN 'Blood Elf' WHEN 11 THEN 'Draenei'
      ELSE 'Unknown'
    END,
    c.class,
    CASE c.class
      WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter' WHEN 4 THEN 'Rogue'
      WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight' WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage'
      WHEN 9 THEN 'Warlock' WHEN 11 THEN 'Druid'
      ELSE 'Unknown'
    END,
    CASE
      WHEN c.race IN (1,3,4,7,11) THEN 'Alliance'
      WHEN c.race IN (2,5,6,8,9,10) THEN 'Horde'
      ELSE 'Unknown'
    END,
    c.gender,
    c.level,
    c.money,
    COALESCE(cap.total_points, 0),
    COALESCE(cap.total_achievements, 0),
    c.totaltime,
    c.totalHonorPoints,
    c.chosenTitle,
    c.knownTitles
  FROM acore_characters.characters c
  JOIN acore_auth.account a ON a.id = c.account
  LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
  WHERE a.username NOT LIKE 'RNDBOT%'
  ORDER BY c.totaltime DESC;
" | python3 -c "
import sys, json, datetime, os
from collections import defaultdict

def iso(unix_ts):
    try:
        ts = int(unix_ts)
    except (TypeError, ValueError):
        return None
    if ts <= 0:
        return None
    return datetime.datetime.utcfromtimestamp(ts).strftime('%Y-%m-%dT%H:%M:%SZ')

# Achievements carry their real completion date straight from
# character_achievement.date (Blizzard's own record) — no tracking needed.
achievements_by_guid = defaultdict(list)
with open('$ACHIEVEMENTS_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, achievement_id, earned_unix = line.split('\t')
        achievements_by_guid[int(guid)].append({
            'id': int(achievement_id),
            'earned_at': iso(earned_unix),
        })

# Currently-equipped item entries per character (bag=0, slot 0-18 — actual
# gear, not bags/bank). Also kept per-slot (equipped_gear_by_guid) for the
# plain current-loadout snapshot - see equipped_gear below.
equipped_by_guid = defaultdict(set)
equipped_gear_by_guid = defaultdict(list)
with open('$EQUIPPED_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, slot, item_entry, item_name = line.split('\t')
        guid = int(guid)
        equipped_by_guid[guid].add(int(item_entry))
        equipped_gear_by_guid[guid].append({
            'slot': int(slot),
            'id': int(item_entry),
            'name': item_name,
        })

# Known mount/companion-learn spells per character (character_spell has no
# per-row timestamp, unlike character_achievement — that's why every
# collection category uses the same sticky-timestamp fallback below).
known_spells_by_guid = defaultdict(set)
with open('$KNOWN_SPELLS_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, spell_id = line.split('\t')
        known_spells_by_guid[int(guid)].add(int(spell_id))

# Which achievement grants which title, by faction (see the mysql query
# above) — used below to give a Titles entry a real earned_at (the
# granting achievement's own date) instead of falling back to the sticky
# first-detected stamp every other undateable collection uses.
achievement_titles = {}
with open('$ACHIEVEMENT_TITLES_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        achievement_id, title_a, title_h = line.split('\t')
        achievement_titles[int(achievement_id)] = (int(title_a), int(title_h))

# characters.knownTitles: 6 space-separated uint32 chunks (three uint64
# PLAYER__FIELD_KNOWN_TITLES fields, each split into two uint32 - see
# AzerothCore's Player::HasTitle/SetTitle). Bit i of chunk i//32 set means
# the character knows the title whose CharTitles.dbc bit_index
# (chartitles_dbc.Mask_ID) is i - this is the game's own ground truth for
# 'has this title', covering every source (achievement, quest, whatever
# granted it) the same way, unlike every other Collections category here
# which can only detect one specific source.
def decode_known_titles(known_titles_str):
    if not known_titles_str:
        return set()
    bits = set()
    for chunk_index, value in enumerate(int(x) for x in known_titles_str.split()):
        for bit in range(32):
            if value & (1 << bit):
                bits.add(chunk_index * 32 + bit)
    return bits

# (json key, detection kind, defs path) — 'equip' entries have slot_groups
# (matched against currently-equipped items), 'spell' entries have
# spell_ids (matched against known character_spell rows), 'title' entries
# have bit_index (matched against the knownTitles bitmask above). Heirlooms
# are stored here exactly like Legendaries (per-character, equipped-only,
# sticky) — the faction-level de-duplicated display (heirlooms are
# Bind-on-Account and can be mailed between characters) is purely an
# app.js rendering concern, not a detection/storage one.
CATEGORIES = [
    ('sets', 'equip', '$COLLECTION_SETS_DEFS'),
    ('mounts', 'spell', '$COLLECTION_MOUNTS_DEFS'),
    ('companions', 'spell', '$COLLECTION_COMPANIONS_DEFS'),
    ('legendaries', 'equip', '$COLLECTION_LEGENDARIES_DEFS'),
    ('tabards', 'equip', '$COLLECTION_TABARDS_DEFS'),
    ('heirlooms', 'equip', '$COLLECTION_HEIRLOOMS_DEFS'),
    ('titles', 'title', '$COLLECTION_TITLES_DEFS'),
]

def detect_equip(equipped_ids, defs):
    # Earned when the character has at least one item from EVERY slot group
    # equipped right now (each slot group lists interchangeable item ids for
    # that slot — a 10-/25-player token pair, or a Horde/Alliance pair
    # sharing one display name). A single-item slot_groups entry ([[id]])
    # reduces to 'is this exact item equipped' — how Legendaries/Tabards/
    # Heirlooms use this same function.
    earned = []
    for entry in defs:
        if all(any(item_id in equipped_ids for item_id in group) for group in entry['slot_groups']):
            earned.append(entry['id'])
    return earned

def detect_spell(known_spell_ids, defs):
    # Shared by Mounts and Companions: earned when the character knows ANY
    # ONE of its spell_ids — multi-color mounts (Netherwing Drake, Qiraji
    # Battle Tank) list every color's spell id and complete on any single
    # color, never requiring every color.
    earned = []
    for entry in defs:
        if any(spell_id in known_spell_ids for spell_id in entry['spell_ids']):
            earned.append(entry['id'])
    return earned

def detect_title(known_titles_str, defs):
    # Titles: earned when the character's knownTitles bitmask has the bit
    # for this entry's bit_index set - the same bitmask the game itself
    # checks, so this catches a title regardless of how it was granted.
    known_bits = decode_known_titles(known_titles_str)
    return [entry['id'] for entry in defs if entry['bit_index'] in known_bits]

DETECTORS = {'equip': detect_equip, 'spell': detect_spell, 'title': detect_title}

defs_by_key = {}
for key, kind, defs_path in CATEGORIES:
    try:
        with open(defs_path) as f:
            defs_by_key[key] = json.load(f)
    except FileNotFoundError:
        # Every other category ships its defs file with the repo - only
        # Titles can legitimately be missing, until its one-time
        # chartitles_dbc export (scripts/generate-titles-collection-
        # data.py) has been run and committed. Skip it gracefully rather
        # than failing the whole export over one not-yet-generated file.
        if key != 'titles':
            raise
        print(f'  Note: {defs_path} not found - skipping Titles detection this run', file=sys.stderr)
        defs_by_key[key] = []

# CharTitles bit_index -> id, for resolving characters.chosenTitle (which
# stores a bit_index, same as knownTitles) into active_title_id below.
title_bit_index_to_id = {entry['bit_index']: entry['id'] for entry in defs_by_key.get('titles', [])}

# Sticky, with the original earned_at preserved: once earned, a collection
# is never removed and its earned_at is never overwritten, even after the
# gear is swapped away. Read whatever was already published last run (if
# any) and carry its earned_at forward for anything still present.
def _earned_at_map(entries):
    # entries used to be bare ids (pre-earned_at); accept both
    return {
        (entry['id'] if isinstance(entry, dict) else entry):
            (entry.get('earned_at') if isinstance(entry, dict) else None)
        for entry in entries
    }

previous_by_key_by_guid = {key: defaultdict(dict) for key, _, _ in CATEGORIES}
prev_path = '$REPO_DATA_DIR/characters.json'
if os.path.exists(prev_path):
    try:
        with open(prev_path) as f:
            previous_data = json.load(f)
        for prev_char in previous_data.get('characters', []):
            prev_collections = prev_char.get('collections', {})
            for key, _, _ in CATEGORIES:
                previous_by_key_by_guid[key][prev_char['guid']] = _earned_at_map(prev_collections.get(key, []))
    except (json.JSONDecodeError, OSError):
        pass  # first run, or an unreadable/corrupt previous file — start fresh

generated_at = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

characters = []
for line in sys.stdin:
    line = line.rstrip('\n')
    if not line:
        continue
    (guid, name, account, race, race_name, cls, class_name, faction, gender,
     level, money, ap, ac, played, honor, chosen_title, known_titles) = line.split('\t')
    guid = int(guid)

    equipped_ids = equipped_by_guid.get(guid, set())
    known_spells = known_spells_by_guid.get(guid, set())
    detector_input_by_kind = {'equip': equipped_ids, 'spell': known_spells, 'title': known_titles}

    # Real dates for titles attributable to one of this character's own
    # completed achievements (title_A for Alliance, title_H for Horde) -
    # every other known title falls back to the sticky stamp below, same
    # as every other undateable collection category.
    real_title_dates = {}
    for ach in achievements_by_guid.get(guid, []):
        title_a, title_h = achievement_titles.get(ach['id'], (0, 0))
        title_id = title_a if faction == 'Alliance' else title_h if faction == 'Horde' else 0
        if title_id and ach['earned_at']:
            real_title_dates[title_id] = ach['earned_at']

    collections = {}
    for key, kind, _ in CATEGORIES:
        detector = DETECTORS[kind]
        current_ids = detector(detector_input_by_kind[kind], defs_by_key[key])
        earned_at_map = dict(previous_by_key_by_guid[key].get(guid, {}))
        for entry_id in current_ids:
            real_date = real_title_dates.get(entry_id) if key == 'titles' else None
            if real_date:
                # Always prefer the real, achievement-sourced date, even
                # over an earned_at already sticky-recorded from before
                # this cross-reference existed.
                earned_at_map[entry_id] = real_date
            else:
                earned_at_map.setdefault(entry_id, generated_at)
        collections[key] = [
            {'id': entry_id, 'earned_at': earned_at}
            for entry_id, earned_at in sorted(earned_at_map.items())
        ]

    active_title_id = title_bit_index_to_id.get(int(chosen_title)) if int(chosen_title) else None

    characters.append({
        'guid': guid,
        'name': name,
        'account': account,
        'race_id': int(race),
        'race_name': race_name,
        'class_id': int(cls),
        'class_name': class_name,
        'faction': faction,
        'gender': int(gender),
        'level': int(level),
        'money_copper': int(money),
        'achievement_points': int(ap),
        'achievement_count': int(ac),
        'played_time_seconds': int(played),
        'honor_points': int(honor),
        'active_title_id': active_title_id,
        'achievements': sorted(achievements_by_guid.get(guid, []), key=lambda a: a['id']),
        'collections': collections,
        'equipped_gear': sorted(equipped_gear_by_guid.get(guid, []), key=lambda g: g['slot']),
    })

with open('$BACKUP_DIR/characters.json', 'w') as f:
    json.dump({'generated_at': generated_at, 'characters': characters}, f, indent=2)

public_characters = [{k: v for k, v in c.items() if k != 'account'} for c in characters]
with open('$REPO_DATA_DIR/characters.json', 'w') as f:
    json.dump({'generated_at': generated_at, 'characters': public_characters}, f, indent=2)

print(f'  characters.json: wrote {len(characters)} characters')
" || { echo "Failed: characters.json export"; exit 1; }
rm -f "$ACHIEVEMENTS_TMP" "$EQUIPPED_TMP" "$KNOWN_SPELLS_TMP" "$ACHIEVEMENT_TITLES_TMP"

echo "  Publishing characters.json to GitHub..."
(
  cd "$REPO_DATA_DIR" \
    && git add characters.json \
    && if ! git diff --cached --quiet; then
         git commit -m "Update character data $TIMESTAMP" \
           && git push origin main
       else
         echo "  No character data changes to publish."
       fi
) || echo "  Warning: failed to publish characters.json to GitHub (non-fatal)"

echo "  Compressing..."
gzip "$BACKUP_DIR"/*.sql || { echo "Failed to compress"; exit 1; }

echo "  Local backup complete: $BACKUP_DIR"

# ── STEP 2: Upload to Google Drive ───────────────────────────────────────────
echo
echo "[2/4] Uploading to Google Drive..."
rclone copy "$BACKUP_DIR" "$GDRIVE_REMOTE/backups/$TIMESTAMP" --progress \
  || { echo "Google Drive upload failed"; exit 1; }

# ── STEP 3: Screenshots ───────────────────────────────────────────────────────
echo
echo "[3/4] Syncing screenshots to Google Drive..."
rclone copy "$SCREENSHOT_SRC" "$GDRIVE_REMOTE/screenshots" --progress \
  || { echo "Google Drive screenshot sync failed"; exit 1; }

# ── STEP 4: Rotate old backups (count-based) ──────────────────────────────────
echo
echo "[4/4] Rotating old backups..."

echo "  Keeping latest $KEEP_LOCAL_COUNT local backups..."
ls -1dt "$FULL_BASE"/*/ | tail -n +$((KEEP_LOCAL_COUNT + 1)) | xargs -r rm -rf \
  && echo "  Local rotation done." \
  || echo "  Warning: local rotation had issues (non-fatal)"

echo "  Keeping latest $KEEP_DRIVE_COUNT Drive backups..."
DRIVE_DIRS=$(rclone lsf "$GDRIVE_REMOTE/backups/" --dirs-only | sort | head -n -$KEEP_DRIVE_COUNT)
if [ -n "$DRIVE_DIRS" ]; then
  echo "$DRIVE_DIRS" | while read -r dir; do
    rclone purge "$GDRIVE_REMOTE/backups/$dir" \
      && echo "  Deleted Drive backup: $dir" \
      || echo "  Warning: failed to delete $dir (non-fatal)"
  done
else
  echo "  No Drive backups to prune."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "======================================="
echo "Backup Complete!"
echo "  Local: $BACKUP_DIR"
echo "  Drive: $GDRIVE_REMOTE/backups/$TIMESTAMP"
echo "  Drive screenshots: $GDRIVE_REMOTE/screenshots"
echo "======================================="
echo
echo "Progress:"
cat "$BACKUP_DIR/playtime_by_character.txt"
echo
echo "Backup contents:"
ls -lh "$BACKUP_DIR"
