#!/bin/bash
set -e

# === WoW Backup ===
# Databases backed up:
#   acore_auth        - CRITICAL: accounts
#   acore_characters  - CRITICAL: character progress
#
# Intentionally excluded:
#   acore_world       - auto-regenerated by worldserver on first start
#   acore_playerbots  - bot state only, acceptable to lose
#
# Retention (count-based, safe for irregular backup schedules):
#   Local backups:  keep last KEEP_LOCAL_COUNT
#   Drive backups:  keep last KEEP_DRIVE_COUNT

# === PATHS ===
FULL_BASE="/home/deck/azerothcore/backups"
SCREENSHOT_SRC="/home/deck/.steam/steam/userdata/1631191323/760/remote/15764481545068347392/screenshots"
GDRIVE_REMOTE="wow-backup:wow-backup"

# === SETTINGS ===
KEEP_LOCAL_COUNT=10   # Keep this many most-recent local backups
KEEP_DRIVE_COUNT=20   # Keep this many most-recent Drive backups

TIMESTAMP=$(date +%F_%H-%M)
BACKUP_DIR="$FULL_BASE/$TIMESTAMP"

# ── STEP 0: Stop servers ──────────────────────────────────────────────────────
echo
echo "[0/4] Stopping servers..."

if pgrep -x worldserver > /dev/null; then
  echo "  Stopping worldserver..."
  pkill -SIGINT -f "worldserver"
  echo "  Waiting for worldserver to shut down..."
  while pgrep -x worldserver > /dev/null; do
    sleep 1
  done
  echo "  ✅ worldserver stopped."
else
  echo "  worldserver not running — skipping."
fi

if pgrep -x authserver > /dev/null; then
  echo "  Stopping authserver..."
  pkill -SIGINT -f "authserver"
  echo "  Waiting for authserver to shut down..."
  while pgrep -x authserver > /dev/null; do
    sleep 1
  done
  echo "  ✅ authserver stopped."
else
  echo "  authserver not running — skipping."
fi

mkdir -p "$BACKUP_DIR" || { echo "Failed to create backup dir"; exit 1; }

echo "======================================="
echo "WoW Backup Started"
echo "Timestamp: $TIMESTAMP"
echo "Backup dir: $BACKUP_DIR"
echo "======================================="

# ── STEP 1: Dump databases ───────────────────────────────────────────────────
echo
echo "[1/4] Dumping databases..."

echo "  Dumping acore_auth..."
mysqldump --no-tablespaces -h 127.0.0.1 -u acore -pacore acore_auth \
  > "$BACKUP_DIR/acore_auth.sql" || { echo "Failed: acore_auth dump"; exit 1; }

echo "  Dumping acore_characters..."
mysqldump --no-tablespaces -h 127.0.0.1 -u acore -pacore acore_characters \
  > "$BACKUP_DIR/acore_characters.sql" || { echo "Failed: acore_characters dump"; exit 1; }

echo "  Saving progress report..."

{
  echo "=== Server Version ==="
  echo "AzerothCore last update: $(cd /home/deck/azerothcore && git log -1 --format='%ci')"
  echo "Playerbots last update: $(cd /home/deck/azerothcore/modules/mod-playerbots && git log -1 --format='%ci')"
  echo

  echo "=== Alliance ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT
      CONCAT(
        c.name, ': ',
        CASE c.race
          WHEN 1 THEN 'Human' WHEN 3 THEN 'Dwarf' WHEN 4 THEN 'Night Elf'
          WHEN 7 THEN 'Gnome' WHEN 11 THEN 'Draenei' ELSE 'Unknown'
        END, ', ',
        CASE c.class
          WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter'
          WHEN 4 THEN 'Rogue' WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight'
          WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage' WHEN 9 THEN 'Warlock'
          WHEN 11 THEN 'Druid' ELSE 'Unknown'
        END,
        ' | Level: ', c.level,
        ' | Money: ', FLOOR(c.money / 10000), 'g',
        ' | Achievements: ', COALESCE(cap.total_points, 0), 'pts (', COALESCE(cap.total_achievements, 0), ')',
        ' | Played: ', FLOOR(c.totaltime / 3600), 'hrs'
      )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (1,3,4,7,11)
    ORDER BY c.totaltime DESC;
  "

  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Total: Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (1,3,4,7,11);
  "

  echo
  echo "=== Horde ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT
      CONCAT(
        c.name, ': ',
        CASE c.race
          WHEN 2 THEN 'Orc' WHEN 5 THEN 'Undead' WHEN 6 THEN 'Tauren'
          WHEN 8 THEN 'Troll' WHEN 9 THEN 'Goblin' WHEN 10 THEN 'Blood Elf' ELSE 'Unknown'
        END, ', ',
        CASE c.class
          WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter'
          WHEN 4 THEN 'Rogue' WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight'
          WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage' WHEN 9 THEN 'Warlock'
          WHEN 11 THEN 'Druid' ELSE 'Unknown'
        END,
        ' | Level: ', c.level,
        ' | Money: ', FLOOR(c.money / 10000), 'g',
        ' | Achievements: ', COALESCE(cap.total_points, 0), 'pts (', COALESCE(cap.total_achievements, 0), ')',
        ' | Played: ', FLOOR(c.totaltime / 3600), 'hrs'
      )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (2,5,6,8,9,10)
    ORDER BY c.totaltime DESC;
  "

  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Total: Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%'
      AND c.race IN (2,5,6,8,9,10);
  "

  echo
  echo "=== Grand Total ==="
  mysql -h 127.0.0.1 -u acore -pacore -N -e "
    SELECT CONCAT(
      'Money: ', FLOOR(SUM(c.money) / 10000), 'g',
      ' | Achievements: ', COALESCE(SUM(cap.total_points), 0), 'pts (', COALESCE(SUM(cap.total_achievements), 0), ')',
      ' | Played: ', FLOOR(SUM(c.totaltime) / 3600), 'hrs'
    )
    FROM acore_characters.characters c
    JOIN acore_auth.account a ON c.account = a.id
    LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
    WHERE a.username NOT LIKE 'RNDBOT%';
  "
} > "$BACKUP_DIR/playtime_by_character.txt" || { echo "Failed: progress report export"; exit 1; }

echo "  Saving characters.json..."
REPO_DATA_DIR="/home/deck/wow-armory-data"

# Sync the clone to the latest published state before touching anything in
# it — both so the sticky-collectable merge below reads the true latest
# characters.json (not a stale local copy), and so the commit+push at the
# end of this step is always a clean fast-forward instead of colliding with
# whatever else has been pushed to main since the last backup run (code
# changes, a rename, etc. — this directory is purely an auto-managed
# publish target, never hand-edited, so discarding any local state here is
# always safe).
(cd "$REPO_DATA_DIR" && git fetch origin main && git reset --hard origin/main) \
  || echo "  Warning: failed to sync $REPO_DATA_DIR with origin/main before publishing (non-fatal)"

COLLECTION_SETS_DEFS="$REPO_DATA_DIR/assets/data/collections/sets.json"
COLLECTION_MOUNTS_DEFS="$REPO_DATA_DIR/assets/data/collections/mounts.json"
COLLECTION_COMPANIONS_DEFS="$REPO_DATA_DIR/assets/data/collections/companions.json"
COLLECTION_LEGENDARIES_DEFS="$REPO_DATA_DIR/assets/data/collections/legendaries.json"
COLLECTION_TABARDS_DEFS="$REPO_DATA_DIR/assets/data/collections/tabards.json"
COLLECTION_HEIRLOOMS_DEFS="$REPO_DATA_DIR/assets/data/collections/heirlooms.json"
COLLECTION_TITLES_DEFS="$REPO_DATA_DIR/assets/data/collections/titles.json"
TALENT_SPELLS_DEFS="$REPO_DATA_DIR/assets/data/talent_spells.json"
ACHIEVEMENTS_TMP="$(mktemp)"
EQUIPPED_TMP="$(mktemp)"
KNOWN_SPELLS_TMP="$(mktemp)"
TALENTS_TMP="$(mktemp)"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ca.guid, ca.achievement, ca.date
  FROM acore_characters.character_achievement ca
  JOIN acore_characters.characters c ON c.guid = ca.guid
  JOIN acore_auth.account a ON a.id = c.account
  WHERE a.username NOT LIKE 'RNDBOT%';
" > "$ACHIEVEMENTS_TMP"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ci.guid, ci.slot, ii.itemEntry, it.name, it.Quality, it.ItemLevel
  FROM acore_characters.character_inventory ci
  JOIN acore_characters.item_instance ii ON ii.guid = ci.item
  JOIN acore_characters.characters c ON c.guid = ci.guid
  JOIN acore_auth.account a ON a.id = c.account
  JOIN acore_world.item_template it ON it.entry = ii.itemEntry
  WHERE ci.bag = 0 AND ci.slot BETWEEN 0 AND 18
    AND a.username NOT LIKE 'RNDBOT%';
" > "$EQUIPPED_TMP"
# Only the spell ids that actually matter for Mounts/Companions detection —
# a max-level character can know thousands of spells, so filtering
# server-side keeps this cheap. Both categories share this one query.
SPELL_COLLECTION_IDS="$(python3 -c "
import json
ids = set()
for path in ('$COLLECTION_MOUNTS_DEFS', '$COLLECTION_COMPANIONS_DEFS'):
    with open(path) as f:
        defs = json.load(f)
    ids.update(str(s) for d in defs for s in d['spell_ids'])
print(','.join(sorted(ids)) if ids else '0')
")"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT cs.guid, cs.spell
  FROM acore_characters.character_spell cs
  JOIN acore_characters.characters c ON c.guid = cs.guid
  JOIN acore_auth.account a ON a.id = c.account
  WHERE cs.spell IN ($SPELL_COLLECTION_IDS)
    AND a.username NOT LIKE 'RNDBOT%';
" > "$KNOWN_SPELLS_TMP"
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT ct.guid, ct.spell, ct.specMask
  FROM acore_characters.character_talent ct
  JOIN acore_characters.characters c ON c.guid = ct.guid
  JOIN acore_auth.account a ON a.id = c.account
  WHERE a.username NOT LIKE 'RNDBOT%';
" > "$TALENTS_TMP"
# Quests: character_queststatus_rewarded holds one row per quest ever
# turned in, but the server itself doesn't treat every row as currently
# "completed" - its own CHAR_SEL_CHARACTER_QUESTSTATUSREW prepared
# statement (which rebuilds a character's rewarded-quest set on login)
# filters WHERE active = 1, and a dedicated UPDATE statement exists to
# flip a specific quest back to active = 0. Matching that same filter
# below, rather than a plain COUNT(*), keeps this in sync with what the
# game itself currently considers "completed" for that character.
mysql -h 127.0.0.1 -u acore -pacore -N -B -e "
  SELECT
    c.guid,
    c.name,
    a.username,
    c.race,
    CASE c.race
      WHEN 1 THEN 'Human' WHEN 2 THEN 'Orc' WHEN 3 THEN 'Dwarf' WHEN 4 THEN 'Night Elf'
      WHEN 5 THEN 'Undead' WHEN 6 THEN 'Tauren' WHEN 7 THEN 'Gnome' WHEN 8 THEN 'Troll'
      WHEN 9 THEN 'Goblin' WHEN 10 THEN 'Blood Elf' WHEN 11 THEN 'Draenei'
      ELSE 'Unknown'
    END,
    c.class,
    CASE c.class
      WHEN 1 THEN 'Warrior' WHEN 2 THEN 'Paladin' WHEN 3 THEN 'Hunter' WHEN 4 THEN 'Rogue'
      WHEN 5 THEN 'Priest' WHEN 6 THEN 'Death Knight' WHEN 7 THEN 'Shaman' WHEN 8 THEN 'Mage'
      WHEN 9 THEN 'Warlock' WHEN 11 THEN 'Druid'
      ELSE 'Unknown'
    END,
    CASE
      WHEN c.race IN (1,3,4,7,11) THEN 'Alliance'
      WHEN c.race IN (2,5,6,8,9,10) THEN 'Horde'
      ELSE 'Unknown'
    END,
    c.level,
    c.money,
    COALESCE(cap.total_points, 0),
    COALESCE(cap.total_achievements, 0),
    c.totaltime,
    c.totalHonorPoints,
    c.logout_time,
    COALESCE(cs.maxhealth, 0),
    COALESCE(cs.strength, 0),
    COALESCE(cs.agility, 0),
    COALESCE(cs.stamina, 0),
    COALESCE(cs.intellect, 0),
    COALESCE(cs.spirit, 0),
    COALESCE(cs.armor, 0),
    COALESCE(cs.resHoly, 0),
    COALESCE(cs.resFire, 0),
    COALESCE(cs.resNature, 0),
    COALESCE(cs.resFrost, 0),
    COALESCE(cs.resShadow, 0),
    COALESCE(cs.resArcane, 0),
    COALESCE(cs.blockPct, 0),
    COALESCE(cs.dodgePct, 0),
    COALESCE(cs.parryPct, 0),
    COALESCE(cs.critPct, 0),
    COALESCE(cs.rangedCritPct, 0),
    COALESCE(cs.spellCritPct, 0),
    COALESCE(cs.attackPower, 0),
    COALESCE(cs.rangedAttackPower, 0),
    COALESCE(cs.spellPower, 0),
    COALESCE(cs.resilience, 0),
    c.activeTalentGroup,
    COALESCE(qc.quest_count, 0)
  FROM acore_characters.characters c
  JOIN acore_auth.account a ON a.id = c.account
  LEFT JOIN acore_characters.character_achievement_points cap ON cap.guid = c.guid
  LEFT JOIN acore_characters.character_stats cs ON cs.guid = c.guid
  LEFT JOIN (
    SELECT guid, COUNT(*) AS quest_count
    FROM acore_characters.character_queststatus_rewarded
    WHERE active = 1
    GROUP BY guid
  ) qc ON qc.guid = c.guid
  WHERE a.username NOT LIKE 'RNDBOT%'
  ORDER BY c.totaltime DESC;
" | python3 -c "
import sys, json, datetime, os
from collections import defaultdict

def iso(unix_ts):
    try:
        ts = int(unix_ts)
    except (TypeError, ValueError):
        return None
    if ts <= 0:
        return None
    return datetime.datetime.utcfromtimestamp(ts).strftime('%Y-%m-%dT%H:%M:%SZ')

# Achievements carry their real completion date straight from
# character_achievement.date (Blizzard's own record) — no tracking needed.
achievements_by_guid = defaultdict(list)
with open('$ACHIEVEMENTS_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, achievement_id, earned_unix = line.split('\t')
        achievements_by_guid[int(guid)].append({
            'id': int(achievement_id),
            'earned_at': iso(earned_unix),
        })

# Currently-equipped item entries per character (bag=0, slot 0-18 — actual
# gear, not bags/bank). Also kept per-slot (equipped_gear_by_guid) for the
# plain current-loadout snapshot - see equipped_gear below.
equipped_by_guid = defaultdict(set)
equipped_gear_by_guid = defaultdict(list)
with open('$EQUIPPED_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, slot, item_entry, item_name, quality, item_level = line.split('\t')
        guid = int(guid)
        equipped_by_guid[guid].add(int(item_entry))
        equipped_gear_by_guid[guid].append({
            'slot': int(slot),
            'id': int(item_entry),
            'name': item_name,
            'quality': int(quality),
            'item_level': int(item_level),
        })

# Known mount/companion-learn spells per character (character_spell has no
# per-row timestamp, unlike character_achievement — that's why every
# collection category uses the same sticky-timestamp fallback below).
known_spells_by_guid = defaultdict(set)
with open('$KNOWN_SPELLS_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, spell_id = line.split('\t')
        known_spells_by_guid[int(guid)].add(int(spell_id))

with open('$TALENT_SPELLS_DEFS') as f:
    talent_spells = {int(k): v for k, v in json.load(f).items()}

talents_by_guid = defaultdict(list)
with open('$TALENTS_TMP') as f:
    for line in f:
        line = line.rstrip('\n')
        if not line:
            continue
        guid, spell_id, spec_mask = line.split('\t')
        talents_by_guid[int(guid)].append((int(spell_id), int(spec_mask)))

# Titles: an achievement id -> title name map (see
# scripts/generate-titles-collection-data.py). A character's titles are
# whichever of their own completed achievements (achievements_by_guid
# above) grant one - no separate query, no sticky merge needed, since
# achievements are already fully known and authoritative every run.
with open('$COLLECTION_TITLES_DEFS') as f:
    titles_by_achievement_id = {entry['id']: entry for entry in json.load(f)}

# (json key, detection kind, defs path) — 'equip' entries have slot_groups
# (matched against currently-equipped items), 'spell' entries have
# spell_ids (matched against known character_spell rows). Heirlooms are
# stored here exactly like Legendaries (per-character, equipped-only,
# sticky) — the faction-level de-duplicated display (heirlooms are
# Bind-on-Account and can be mailed between characters) is purely an
# app.js rendering concern, not a detection/storage one. Titles isn't
# here - see the dedicated block below.
CATEGORIES = [
    ('sets', 'equip', '$COLLECTION_SETS_DEFS'),
    ('mounts', 'spell', '$COLLECTION_MOUNTS_DEFS'),
    ('companions', 'spell', '$COLLECTION_COMPANIONS_DEFS'),
    ('legendaries', 'equip', '$COLLECTION_LEGENDARIES_DEFS'),
    ('tabards', 'equip', '$COLLECTION_TABARDS_DEFS'),
    ('heirlooms', 'equip', '$COLLECTION_HEIRLOOMS_DEFS'),
]

def detect_equip(equipped_ids, defs):
    # Earned when the character has at least one item from EVERY slot group
    # equipped right now (each slot group lists interchangeable item ids for
    # that slot — a 10-/25-player token pair, or a Horde/Alliance pair
    # sharing one display name). A single-item slot_groups entry ([[id]])
    # reduces to 'is this exact item equipped' — how Legendaries/Tabards/
    # Heirlooms use this same function.
    earned = []
    for entry in defs:
        if all(any(item_id in equipped_ids for item_id in group) for group in entry['slot_groups']):
            earned.append(entry['id'])
    return earned

def detect_spell(known_spell_ids, defs):
    # Shared by Mounts and Companions: earned when the character knows ANY
    # ONE of its spell_ids — multi-color mounts (Netherwing Drake, Qiraji
    # Battle Tank) list every color's spell id and complete on any single
    # color, never requiring every color.
    earned = []
    for entry in defs:
        if any(spell_id in known_spell_ids for spell_id in entry['spell_ids']):
            earned.append(entry['id'])
    return earned

DETECTORS = {'equip': detect_equip, 'spell': detect_spell}

defs_by_key = {}
for key, kind, defs_path in CATEGORIES:
    with open(defs_path) as f:
        defs_by_key[key] = json.load(f)

# Sticky, with the original earned_at preserved: once earned, a collection
# is never removed and its earned_at is never overwritten, even after the
# gear is swapped away. Read whatever was already published last run (if
# any) and carry its earned_at forward for anything still present.
def _earned_at_map(entries):
    # entries used to be bare ids (pre-earned_at); accept both
    return {
        (entry['id'] if isinstance(entry, dict) else entry):
            (entry.get('earned_at') if isinstance(entry, dict) else None)
        for entry in entries
    }

previous_by_key_by_guid = {key: defaultdict(dict) for key, _, _ in CATEGORIES}
prev_path = '$REPO_DATA_DIR/characters.json'
if os.path.exists(prev_path):
    try:
        with open(prev_path) as f:
            previous_data = json.load(f)
        for prev_char in previous_data.get('characters', []):
            prev_collections = prev_char.get('collections', {})
            for key, _, _ in CATEGORIES:
                previous_by_key_by_guid[key][prev_char['guid']] = _earned_at_map(prev_collections.get(key, []))
    except (json.JSONDecodeError, OSError):
        pass  # first run, or an unreadable/corrupt previous file — start fresh

generated_at = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

# Named, not positional, unpacking below this point - the main query is now
# wide enough (40 columns, once character_stats joined in) that a flat
# tuple assignment is a silent-corruption risk (a single reorder swaps two
# stats with no error, unlike a crash). Must stay in the exact order the
# SELECT above lists its columns in.
MAIN_QUERY_FIELDS = [
    'guid', 'name', 'account', 'race', 'race_name', 'cls', 'class_name',
    'faction', 'level', 'money', 'ap', 'ac', 'played', 'honor', 'logout',
    'max_health', 'strength', 'agility', 'stamina', 'intellect', 'spirit',
    'armor', 'res_holy', 'res_fire', 'res_nature', 'res_frost', 'res_shadow',
    'res_arcane', 'block_pct', 'dodge_pct', 'parry_pct', 'crit_pct',
    'ranged_crit_pct', 'spell_crit_pct', 'attack_power', 'ranged_attack_power',
    'spell_power', 'resilience', 'active_talent_group', 'quests_completed',
]

characters = []
for line in sys.stdin:
    line = line.rstrip('\n')
    if not line:
        continue
    row = dict(zip(MAIN_QUERY_FIELDS, line.split('\t')))
    guid = int(row['guid'])

    equipped_ids = equipped_by_guid.get(guid, set())
    known_spells = known_spells_by_guid.get(guid, set())

    collections = {}
    for key, kind, _ in CATEGORIES:
        detector = DETECTORS[kind]
        current_ids = detector(equipped_ids if kind == 'equip' else known_spells, defs_by_key[key])
        earned_at_map = dict(previous_by_key_by_guid[key].get(guid, {}))
        for entry_id in current_ids:
            earned_at_map.setdefault(entry_id, generated_at)
        collections[key] = [
            {'id': entry_id, 'earned_at': earned_at}
            for entry_id, earned_at in sorted(earned_at_map.items())
        ]

    collections['titles'] = sorted(
        (
            {'id': ach['id'], 'earned_at': ach['earned_at']}
            for ach in achievements_by_guid.get(guid, [])
            if ach['id'] in titles_by_achievement_id
        ),
        key=lambda t: t['id'],
    )

    active_spec_bit = 1 << int(row['active_talent_group'])
    talent_points = defaultdict(int)
    for spell_id, spec_mask in talents_by_guid.get(guid, []):
        if not (spec_mask & active_spec_bit):
            continue
        talent = talent_spells.get(spell_id)
        if talent:
            talent_points[talent['tab_id']] += talent['points']

    characters.append({
        'guid': guid,
        'name': row['name'],
        'account': row['account'],
        'race_id': int(row['race']),
        'race_name': row['race_name'],
        'class_id': int(row['cls']),
        'class_name': row['class_name'],
        'faction': row['faction'],
        'level': int(row['level']),
        'money_copper': int(row['money']),
        'achievement_points': int(row['ap']),
        'achievement_count': int(row['ac']),
        'played_time_seconds': int(row['played']),
        'honor_points': int(row['honor']),
        'last_online': iso(row['logout']),
        'quests_completed': int(row['quests_completed']),
        'stats': {
            'max_health': int(row['max_health']),
            'strength': int(row['strength']),
            'agility': int(row['agility']),
            'stamina': int(row['stamina']),
            'intellect': int(row['intellect']),
            'spirit': int(row['spirit']),
            'armor': int(row['armor']),
            'res_holy': int(row['res_holy']),
            'res_fire': int(row['res_fire']),
            'res_nature': int(row['res_nature']),
            'res_frost': int(row['res_frost']),
            'res_shadow': int(row['res_shadow']),
            'res_arcane': int(row['res_arcane']),
            'block_pct': float(row['block_pct']),
            'dodge_pct': float(row['dodge_pct']),
            'parry_pct': float(row['parry_pct']),
            'crit_pct': float(row['crit_pct']),
            'ranged_crit_pct': float(row['ranged_crit_pct']),
            'spell_crit_pct': float(row['spell_crit_pct']),
            'attack_power': int(row['attack_power']),
            'ranged_attack_power': int(row['ranged_attack_power']),
            'spell_power': int(row['spell_power']),
            'resilience': int(row['resilience']),
        },
        'achievements': sorted(achievements_by_guid.get(guid, []), key=lambda a: a['id']),
        'collections': collections,
        'equipped_gear': sorted(equipped_gear_by_guid.get(guid, []), key=lambda g: g['slot']),
        'talents': dict(talent_points),
    })

with open('$BACKUP_DIR/characters.json', 'w') as f:
    json.dump({'generated_at': generated_at, 'characters': characters}, f, indent=2)

public_characters = [{k: v for k, v in c.items() if k != 'account'} for c in characters]
with open('$REPO_DATA_DIR/characters.json', 'w') as f:
    json.dump({'generated_at': generated_at, 'characters': public_characters}, f, indent=2)

print(f'  characters.json: wrote {len(characters)} characters')
" || { echo "Failed: characters.json export"; exit 1; }
rm -f "$ACHIEVEMENTS_TMP" "$EQUIPPED_TMP" "$KNOWN_SPELLS_TMP" "$TALENTS_TMP"

echo "  Publishing characters.json to GitHub..."
(
  cd "$REPO_DATA_DIR" \
    && git add characters.json \
    && if ! git diff --cached --quiet; then
         git commit -m "Update character data $TIMESTAMP" \
           && git push origin main
       else
         echo "  No character data changes to publish."
       fi
) || echo "  Warning: failed to publish characters.json to GitHub (non-fatal)"

echo "  Compressing..."
gzip "$BACKUP_DIR"/*.sql || { echo "Failed to compress"; exit 1; }

echo "  Local backup complete: $BACKUP_DIR"

# ── STEP 2: Upload to Google Drive ───────────────────────────────────────────
echo
echo "[2/4] Uploading to Google Drive..."
rclone copy "$BACKUP_DIR" "$GDRIVE_REMOTE/backups/$TIMESTAMP" --progress \
  || { echo "Google Drive upload failed"; exit 1; }

# ── STEP 3: Screenshots ───────────────────────────────────────────────────────
echo
echo "[3/4] Syncing screenshots to Google Drive..."
rclone copy "$SCREENSHOT_SRC" "$GDRIVE_REMOTE/screenshots" --progress \
  || { echo "Google Drive screenshot sync failed"; exit 1; }

# ── STEP 4: Rotate old backups (count-based) ──────────────────────────────────
echo
echo "[4/4] Rotating old backups..."

echo "  Keeping latest $KEEP_LOCAL_COUNT local backups..."
ls -1dt "$FULL_BASE"/*/ | tail -n +$((KEEP_LOCAL_COUNT + 1)) | xargs -r rm -rf \
  && echo "  Local rotation done." \
  || echo "  Warning: local rotation had issues (non-fatal)"

echo "  Keeping latest $KEEP_DRIVE_COUNT Drive backups..."
DRIVE_DIRS=$(rclone lsf "$GDRIVE_REMOTE/backups/" --dirs-only | sort | head -n -$KEEP_DRIVE_COUNT)
if [ -n "$DRIVE_DIRS" ]; then
  echo "$DRIVE_DIRS" | while read -r dir; do
    rclone purge "$GDRIVE_REMOTE/backups/$dir" \
      && echo "  Deleted Drive backup: $dir" \
      || echo "  Warning: failed to delete $dir (non-fatal)"
  done
else
  echo "  No Drive backups to prune."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "======================================="
echo "Backup Complete!"
echo "  Local: $BACKUP_DIR"
echo "  Drive: $GDRIVE_REMOTE/backups/$TIMESTAMP"
echo "  Drive screenshots: $GDRIVE_REMOTE/screenshots"
echo "======================================="
echo
echo "Progress:"
cat "$BACKUP_DIR/playtime_by_character.txt"
echo
echo "Backup contents:"
ls -lh "$BACKUP_DIR"
